In [ ]:
34, 25°
60, 35°

In [12]:
from numpy import sin, cos

In [13]:
from numpy import radians

In [14]:
A = [100*cos(radians(15)), 100*sin(radians(15))]

In [15]:
B = [90*cos(radians(35)), 90*sin(radians(35))]

In [16]:
A

[96.59258262890683, 25.881904510252074]

In [17]:
B

[73.72368398600926, 51.621879271594146]

In [33]:
from numpy import matrix, sqrt, arctan2, degrees

In [19]:
A = matrix(A).T

In [20]:
B = matrix(B).T

In [21]:
A

matrix([[96.59258263],
        [25.88190451]])

In [23]:
C = A+B

$$
A = 34 N \angle 25^o =
\begin{pmatrix}
34N \cdot \cos{25^o} \\
34N \cdot \sin{25^o}
\end{pmatrix} =
\begin{pmatrix}
30.81 N \\
14.86 N
\end{pmatrix}
$$

In [26]:
C.tolist()

[[170.3162666149161], [77.50378378184622]]

In [30]:
sqrt(C.T*C)

matrix([[187.12153049]])

In [34]:
degrees(arctan2(170.31, 77.50))

65.53197040575449

In [35]:
C.T*C

matrix([[35014.46717415]])

In [ ]:
0.2m, 4m/s, 40°, 0.5T

In [4]:
from numpy import cos, radians, sin

In [8]:
sin(radians(40))*0.5*4*0.2

0.2571150438746157

In [9]:
2e-4/3e-7

666.6666666666667

In [ ]:
120V, 100W

In [10]:
100/120

0.8333333333333334

In [11]:
120*120/100

144.0

In [13]:
from scipy.constants import epsilon_0
from numpy import pi

In [17]:
f1 = 1/(4*pi*epsilon_0)*(3e-6*8e-6)/(0.5*0.5)

In [18]:
f2 = 1/(4*pi*epsilon_0)*(3e-6*7e-6)/(0.5*0.5)

In [16]:
from numpy import sqrt

In [19]:
sqrt(f1**2 + f2**2)

1.1464678326148907

In [20]:
60*1.25

75.0

In [21]:
75*0.04

3.0